/** @type {import('tailwindcss').Config} */
export default {
    content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "on-secondary": "#ffffff",
                "on-tertiary-container": "#711419",
                "on-surface-variant": "#3c4a42",
                "inverse-primary": "#4edea3",
                "on-secondary-fixed-variant": "#3f465c",
                "on-background": "#131b2e",
                "surface": "#faf8ff",
                "surface-container-high": "#e2e7ff",
                "secondary-container": "#dae2fd",
                "surface-container-highest": "#dae2fd",
                "on-error-container": "#93000a",
                "on-tertiary-fixed": "#410005",
                "inverse-surface": "#283044",
                "secondary": "#565e74",
                "surface-bright": "#faf8ff",
                "surface-container": "#eaedff",
                "tertiary-fixed-dim": "#ffb3af",
                "on-secondary-container": "#5c647a",
                "on-primary": "#ffffff",
                "primary-fixed-dim": "#4edea3",
                "surface-container-low": "#f2f3ff",
                "primary-container": "#10b981",
                "surface-dim": "#d2d9f4",
                "primary-fixed": "#6ffbbe",
                "secondary-fixed-dim": "#bec6e0",
                "outline-variant": "#bbcabf",
                "on-primary-fixed-variant": "#005236",
                "on-tertiary": "#ffffff",
                "primary": "#006c49",
                "secondary-fixed": "#dae2fd",
                "background": "#faf8ff",
                "surface-container-lowest": "#ffffff",
                "on-secondary-fixed": "#131b2e",
                "on-tertiary-fixed-variant": "#842225",
                "on-primary-fixed": "#002113",
                "surface-variant": "#dae2fd",
                "outline": "#6c7a71",
                "on-error": "#ffffff",
                "on-primary-container": "#00422b",
                "surface-tint": "#006c49",
                "inverse-on-surface": "#eef0ff",
                "tertiary-container": "#fc7c78",
                "on-surface": "#131b2e",
                "tertiary-fixed": "#ffdad7",
                "tertiary": "#a43a3a",
                "error": "#ba1a1a",
                "error-container": "#ffdad6"
            },
            fontFamily: {
                "headline": ["IBM Plex Sans", "sans-serif"],
                "body": ["Inter", "sans-serif"],
                "label": ["Inter", "sans-serif"],
                "display": ["Work Sans", "sans-serif"]
            },
            borderRadius: {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
        },
    },
    plugins: [],
}
